In [1]:
import numpy
from sklearn import datasets, metrics
from sklearn.tree import DecisionTreeClassifier

X,y=datasets.load_iris(return_X_y=True)
print(X)
print(y)

X_train=X[range(0,150,2),:]
y_train=y[range(0,150,2)]

X_test=X[range(1,150,2),:]
y_test=y[range(1,150,2)]

clf = DecisionTreeClassifier(criterion='entropy') #creating instance of a classifier
#default criterion is gini

clf.fit(X_train, y_train)
prediction = clf.predict(X_test) #predict using the learnt classifier

print("############### Predictions #################")
print(prediction)
print("#############################################")

print("Accuracy:",metrics.accuracy_score(y_test, prediction, normalize=True))

print(metrics.classification_report(y_test, prediction))
print(metrics.confusion_matrix(y_test, prediction))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [2]:
import numpy
from sklearn import neighbors, datasets, metrics
from sklearn.model_selection import GridSearchCV

X, y=datasets.load_iris(return_X_y=True) #Loading the Iris Dataset

X_train=X[range(0,150,2),:]
y_train=y[range(0,150,2)]

X_test=X[range(1,150,2),:]
y_test=y[range(1,150,2)]

#creating instance of a classifier
clf = neighbors.KNeighborsClassifier()

#param_grid should be dictionary or list of dictionaries
#Specify hyperparameters which you want to tune

#If some hyperparameter you don't want to tune, specify that parameter
#while creating instance of the classifier

param_grid = [
  {'n_neighbors': [1, 5, 10, 20], 'weights': ['uniform', 'distance']} ]

clf_gs=GridSearchCV(clf,param_grid,cv=5)
#there is a refit argument whose default is True

clf_gs.fit(X_train, y_train)

#Print best parameters
print(clf_gs.best_params_)

prediction = clf_gs.predict(X_test) #predict using the learnt classifier

print("############### Predictions #################")
print(prediction)
print("#############################################")

print("Accuracy = ", metrics.accuracy_score(y_test, prediction, normalize=True))

print(metrics.classification_report(y_test, prediction))

print(metrics.confusion_matrix(y_test, prediction))

{'n_neighbors': 5, 'weights': 'uniform'}
############### Predictions #################
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
#############################################
Accuracy =  0.9866666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      0.96      0.98        25
           2       0.96      1.00      0.98        25

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75

[[25  0  0]
 [ 0 24  1]
 [ 0  0 25]]
